Cleanup project files
appany/Minio.AspNetCore pull request #61
Opened 2023-05-02 15:21 UTC by martijn00

2023-05-05 09:47 UTC, martijn00 commented
@sergeyshaykhullin Minio has been updated to 5.0.0. Can you merge this and release a 5.0.0 version as well?

2023-05-05 12:10 UTC, sergeyshaykhullin commented on src/Minio.AspNetCore/MinioClientFactory.cs
> +      using var client = new MinioClient()
Does this using will dispose client and return disposed instance from CreateClient?

2023-05-05 12:13 UTC, sergeyshaykhullin commented on src/Minio.AspNetCore/MinioClientFactory.cs
> +      using var client = new MinioClient()
It seems like IMinioClientFactory owner is responsible to add usings from calling side

2023-05-05 12:13 UTC, sergeyshaykhullin requested changes
Thank you for your project cleanup

I have one question about disposing MinioClient from factory

2023-05-05 12:25 UTC, martijn00 commented
@sergeyshaykhullin done

2023-05-05 12:55 UTC, martijn00 commented
@sergeyshaykhullin fixed the test now

2023-05-05 14:17 UTC, merged

2023-05-06 13:18 UTC, martijn00 commented
@sergeyshaykhullin thanks! Can you push a new nuget release?

2023-05-06 13:21 UTC, sergeyshaykhullin commented
@martijn00 There are some problems with CI

Can you please check CI changes?